### ISSUE TITLE
Add support for GDTask.Current

### ISSUE THREAD

**Issue by MrModez** [Fractural/GDTask#11]
Thank you for this library!
Is it possible to add support for GDTask.CurrentId similar to Task.CurrentId?
In my case I need to figure out which task I'm in, to create a subtask.

**Comment by Atlinx** [comment]
Most of the source code is from the UniTask library, and I'm not sure if UniTask implements any way to check which task is currently being run. Maybe you can pass a unique ID into a task function before starting it to manually keep track of what task you're in.
