### ISSUE TITLE
Warnings in DiagnosticsExtensions

### ISSUE THREAD

**Issue by plyoung** [Fractural/GDTask#13]
There are some warnings in DiagnosticsExtensions.cs when net8.0 and PublishAOT is enabled. They can be removed by adding the `RequiresUnreferencedCode` attribute to `CleanupAsyncStackTrace()` and `TryResolveStateMachineMethod()` since those are only called under #DEBUG and PublishAOT can be enabled for ExportRelease only.

I've not properly tested AOT yet so do not know if it is worth the trouble to get rid of these warning but thought I'd share that they exist under that situation.

**Comment by Atlinx** [comment]
Hey, thanks for making this issue! Since this addon is just a 1-to-1 port of UniTask, I'm not quite sure what PublishAOT does. But If you'd like to make a PR that fixes it I'd be happy to merge it in :)

**Comment by Atlinx** [comment]
Closed by #14
